title: <img style="width:64px" src="https://timingkit.tk/img/tk-logo.png"/> TimingKit
email: support@timingkit.tk
description: >
  Analyze time with dashboards and share them with your coworkers, boss or anyone else!
baseurl: ""
url: ""
repository: ZitRos/timingkit-community
service_name: TimingKit
service_url: https://timingkit.tk
author_name: Nikita Savchenko
author_url: https://nikita.tk

theme: jekyll-theme-architect
