title: TimingKit
email: support@timingkit.tk
description: >
  Analyze your time on dashboards which you can share with coworkers, boss or anyone else!
baseurl: ""
url: ""
repository: ZitRos/timingkit-community
service_name: TimingKit
service_url: https://timingkit.tk
author_name: Nikita Savchenko
author_url: https://nikita.tk

theme: jekyll-theme-architect
