title: TimingKit - Calendar Time Analysis Service
email: support@timingkit.tk
description: >
  TimingKit is a young service about time analysis. Build dashboards and
  share them with your coworkers, boss or anyone else! More and more features
  are about to come!
baseurl: ""
url: ""
github.is_project_page: false
github.show_downloads: false

theme: jekyll-theme-architect
