title: TimingKit - Calendar Time Analysis Service
email: support@timingkit.tk
description: >
  TimingKit is a young service about time analysis. Build dashboards and
  share them with your coworkers, boss or anyone else! More and more features
  are about to come!
baseurl: ""
url: ""
repository: ZitRos/timingkit-community
service_name: TimingKit
service_url: https://timingkit.tk
author_name: Nikita Savchenko
author_url: https://nikita.tk

theme: jekyll-theme-cayman