title: <img style="width:64px" src="https://timingkit.tk/img/tk-logo.png"/> TimingKit
email: support@timingkit.tk
description: >
  Analyze time with dashboards and share them with your coworkers, boss or anyone else!
baseurl: ""
url: ""
github.is_user_page: false
github.is_project_page: false
show_downloads: false

theme: jekyll-theme-architect
